### ISSUE TITLE
Duplicated Agents on gitlab.com

### ISSUE THREAD

**Issue by onyame** [DLR-SC/gitlab2prov#45]
On gitlab.com, the same user appear twice in the provenance graph.

For example at repo  https://gitlab.com/onyame/provtest1 the result after giving a "Thumbs Up" (`award_emoji` event):
[provtest1-step3.pdf](https://github.com/DLR-SC/gitlab2prov/files/6560447/provtest1-step3.pdf)

**Comment by cdboer** [comment]
This issue occured, because GitLab returned the two different user names for your account. The first was `fistname lastname` the second one `firstname lastname\s` with a trailing whitespace character. 

The cause for this could be twofold. 
1) Only commit artifacts where attributed to the "wrong" and duplicated agents. This could, as far as we are aware, stem from a faulty git config. Maybe you appended a space to your user name in your config. Although i don't think this was the case, as testing with another gitlab instance did not produce the same issue.
2) There is some fault in the current GitLab version running at `gitlab.com` that returns the name of a user with a trailing whitespace for some actions and without the trailing whitespace for others.

Solution: Sanitize user names. Simply remove trailing whitespace by issuing a call to `str.strip()`.
