### ISSUE TITLE
Add qualified relations

### ISSUE THREAD

**Issue by onyame** [DLR-SC/gitlab2prov#52]
To have [qualified relations](https://patterns.dataincubator.org/book/qualified-relation.html) instead of binary relation between PROV class elements, add attributes to relations, at least:

- `wasGeneratedBy` 
  - `prov:time`
  - `prov:role`
 
- `used`
  - `prov:time`
  - `prov:role`

- `wasInvalidatedBy`
  - `prov:time`

**Comment by cdboer** [comment]
Here some PROV-O links for the mentioned relations:
- [prov:Generation](https://www.w3.org/TR/prov-o/#Generation)
- [prov:Usage](https://www.w3.org/TR/2013/REC-prov-o-20130430/#Usage)
- [prov:Invalidation](https://www.w3.org/TR/2013/REC-prov-o-20130430/#Invalidation)

According to PROV-O the attribute names should be:
- `prov:atTime` instead of `prov:time`
- `prov:hadRole` instead of `prov:role`

**Comment by cdboer** [comment]
This issue will be closed when V1.0 is merged into master. Qualified relations are included in the V1.0 release candidate.
